
services:

  minio:
    hostname: minio
    networks:
      - delta-network
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_REGION_NAME=eu-west-1
      - MINIO_REGION=eu-west-1
    ports:
      - "19000:9000"
      - "19001:9001"
    command: >
      server /data --console-address ':9001'
    volumes:
      - minio-data:/data

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      - delta-network
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minio minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/nessie-warehouse;
      /usr/bin/mc mb minio/nessie-iceberg;
      /usr/bin/mc policy set public minio/nessie-warehouse;
      /usr/bin/mc policy set public minio/nessie-iceberg;
      tail -f /dev/null
      "  

  hive-postgres:
    hostname: hive-postgres
    networks:
      - delta-network
    image: postgres
    container_name: hive-postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_DB=hive_metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hivepass123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"  # PostgreSQL default port
    volumes:
      - postgres-data:/var/lib/postgresql/data 

  hive-metastore:
    image: bitsondatadev/hive-metastore:latest
    container_name: hive-metastore
    networks:
      - delta-network
    environment:
      - HADOOP_OPTIONAL_TOOLS=hadoop-aws
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-postgres:5432/hive_metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hivepass123
    ports:
      - "9083:9083"
    volumes:
      - ${PWD}/hive/metastore-site.xml:/opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml
      # - ${PWD}/hive/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    depends_on:
      - hive-postgres
      - minio

  nessie:
    image: ghcr.io/projectnessie/nessie
    container_name: nessie
    ports:
      - '19120:19120'
    networks:
      - delta-network
    environment:
      - QUARKUS_OTEL_SDK_DISABLED=true
    
  trino:
    image: 'trinodb/trino:472'
    container_name: trino
    networks:
      - delta-network
    ports:
      - '18080:18080'
    volumes:
      - trino-config:/etc/trino

  mypostgres:
    hostname: mypostgres
    networks:
      - delta-network
    image: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=deltalake
      - POSTGRES_PASSWORD=deltalake
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "25432:5432"  # PostgreSQL default port
    volumes:
      - mypostgres-data:/var/lib/postgresql/data 

volumes:
  minio-data:
  postgres-data:
  mypostgres-data:
  trino-config:
    driver: local 
    driver_opts:
      type: none
      device: ./trino/etc
      o: bind

networks:
  delta-network: