version: '2'

services:
  trino:
    image: 'trinodb/trino'
    ports:
      - '18080:18080'
    volumes:
      - trino-config:/etc/trino

volumes:
  trino-config:
    driver: local 
    driver_opts:
      type: none
      device: ./trino/etc
      o: bind